### PR TITLE
use build-in shutdown instead of endless

### PR DESCRIPTION
**Pull request by xqdoo00o**
From example: [doc](https://gin-gonic.com/docs/examples/graceful-restart-or-stop/)
[issue](https://github.com/gin-gonic/gin/pull/3220)
to avoid windows build issue

### CODE REVIEW

**Comment by acheong08** [comment]
I need graceful restart with SIGHUP

**Comment by xqdoo00o** [comment]
> I need graceful restart with SIGHUP

That could implemented use fork process, I think 3rd endless repo does the similar func. Although I think it's unnecessory if could use `kill && start`, I will try that

**Comment by acheong08** [comment]
I tried to add support for windows via https://github.com/acheong08/endless

Can you check if it works? (I don't have access to windows)

**Comment by acheong08** [comment]
I think I just fixed it. Check again.

**Comment by xqdoo00o** [comment]
> I think I just fixed it. Check again.

 new error. undefined: syscall.Kill

**Comment by acheong08** [comment]
> > I think I just fixed it. Check again.
> 
> new error. undefined: syscall.Kill

That was fixed with https://github.com/acheong08/endless/commit/1359fd84c83644e4c62f7a233679f07fa3e449ed

**Comment by xqdoo00o** [comment]
> > > I think I just fixed it. Check again.
> > 
> > 
> > new error. undefined: syscall.Kill
> 
> That was fixed with [acheong08/endless@1359fd8](https://github.com/acheong08/endless/commit/1359fd84c83644e4c62f7a233679f07fa3e449ed)
> 
> Version update might take a bit of time to sync

build success with that commit

**Pull request closed without merging**
